/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSeasonsRouteImport } from './routes/_authenticated.seasons'
import { Route as AuthenticatedSaccosRouteImport } from './routes/_authenticated.saccos'
import { Route as AuthenticatedRiskAssessmentsRouteImport } from './routes/_authenticated.risk-assessments'
import { Route as AuthenticatedLoansRouteImport } from './routes/_authenticated.loans'
import { Route as AuthenticatedFarmersRouteImport } from './routes/_authenticated.farmers'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedSeasonsNewRouteImport } from './routes/_authenticated.seasons.new'
import { Route as AuthenticatedSeasonsSeasonIdRouteImport } from './routes/_authenticated.seasons.$seasonId'
import { Route as AuthenticatedSaccosNewRouteImport } from './routes/_authenticated.saccos.new'
import { Route as AuthenticatedSaccosSaccoIdRouteImport } from './routes/_authenticated.saccos.$saccoId'
import { Route as AuthenticatedRiskAssessmentsAssessmentIdRouteImport } from './routes/_authenticated.risk-assessments.$assessmentId'
import { Route as AuthenticatedLoansNewRouteImport } from './routes/_authenticated.loans.new'
import { Route as AuthenticatedLoansLoanIdRouteImport } from './routes/_authenticated.loans.$loanId'
import { Route as AuthenticatedFarmsNewRouteImport } from './routes/_authenticated.farms.new'
import { Route as AuthenticatedFarmsFarmIdRouteImport } from './routes/_authenticated.farms.$farmId'
import { Route as AuthenticatedFarmersNewRouteImport } from './routes/_authenticated.farmers.new'
import { Route as AuthenticatedFarmersFarmerIdRouteImport } from './routes/_authenticated.farmers.$farmerId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSeasonsRoute = AuthenticatedSeasonsRouteImport.update({
  id: '/seasons',
  path: '/seasons',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSaccosRoute = AuthenticatedSaccosRouteImport.update({
  id: '/saccos',
  path: '/saccos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRiskAssessmentsRoute =
  AuthenticatedRiskAssessmentsRouteImport.update({
    id: '/risk-assessments',
    path: '/risk-assessments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLoansRoute = AuthenticatedLoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFarmersRoute = AuthenticatedFarmersRouteImport.update({
  id: '/farmers',
  path: '/farmers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSeasonsNewRoute = AuthenticatedSeasonsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedSeasonsRoute,
} as any)
const AuthenticatedSeasonsSeasonIdRoute =
  AuthenticatedSeasonsSeasonIdRouteImport.update({
    id: '/$seasonId',
    path: '/$seasonId',
    getParentRoute: () => AuthenticatedSeasonsRoute,
  } as any)
const AuthenticatedSaccosNewRoute = AuthenticatedSaccosNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedSaccosRoute,
} as any)
const AuthenticatedSaccosSaccoIdRoute =
  AuthenticatedSaccosSaccoIdRouteImport.update({
    id: '/$saccoId',
    path: '/$saccoId',
    getParentRoute: () => AuthenticatedSaccosRoute,
  } as any)
const AuthenticatedRiskAssessmentsAssessmentIdRoute =
  AuthenticatedRiskAssessmentsAssessmentIdRouteImport.update({
    id: '/$assessmentId',
    path: '/$assessmentId',
    getParentRoute: () => AuthenticatedRiskAssessmentsRoute,
  } as any)
const AuthenticatedLoansNewRoute = AuthenticatedLoansNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedLoansRoute,
} as any)
const AuthenticatedLoansLoanIdRoute =
  AuthenticatedLoansLoanIdRouteImport.update({
    id: '/$loanId',
    path: '/$loanId',
    getParentRoute: () => AuthenticatedLoansRoute,
  } as any)
const AuthenticatedFarmsNewRoute = AuthenticatedFarmsNewRouteImport.update({
  id: '/farms/new',
  path: '/farms/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFarmsFarmIdRoute =
  AuthenticatedFarmsFarmIdRouteImport.update({
    id: '/farms/$farmId',
    path: '/farms/$farmId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFarmersNewRoute = AuthenticatedFarmersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedFarmersRoute,
} as any)
const AuthenticatedFarmersFarmerIdRoute =
  AuthenticatedFarmersFarmerIdRouteImport.update({
    id: '/$farmerId',
    path: '/$farmerId',
    getParentRoute: () => AuthenticatedFarmersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/farmers': typeof AuthenticatedFarmersRouteWithChildren
  '/loans': typeof AuthenticatedLoansRouteWithChildren
  '/risk-assessments': typeof AuthenticatedRiskAssessmentsRouteWithChildren
  '/saccos': typeof AuthenticatedSaccosRouteWithChildren
  '/seasons': typeof AuthenticatedSeasonsRouteWithChildren
  '/farmers/$farmerId': typeof AuthenticatedFarmersFarmerIdRoute
  '/farmers/new': typeof AuthenticatedFarmersNewRoute
  '/farms/$farmId': typeof AuthenticatedFarmsFarmIdRoute
  '/farms/new': typeof AuthenticatedFarmsNewRoute
  '/loans/$loanId': typeof AuthenticatedLoansLoanIdRoute
  '/loans/new': typeof AuthenticatedLoansNewRoute
  '/risk-assessments/$assessmentId': typeof AuthenticatedRiskAssessmentsAssessmentIdRoute
  '/saccos/$saccoId': typeof AuthenticatedSaccosSaccoIdRoute
  '/saccos/new': typeof AuthenticatedSaccosNewRoute
  '/seasons/$seasonId': typeof AuthenticatedSeasonsSeasonIdRoute
  '/seasons/new': typeof AuthenticatedSeasonsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/farmers': typeof AuthenticatedFarmersRouteWithChildren
  '/loans': typeof AuthenticatedLoansRouteWithChildren
  '/risk-assessments': typeof AuthenticatedRiskAssessmentsRouteWithChildren
  '/saccos': typeof AuthenticatedSaccosRouteWithChildren
  '/seasons': typeof AuthenticatedSeasonsRouteWithChildren
  '/farmers/$farmerId': typeof AuthenticatedFarmersFarmerIdRoute
  '/farmers/new': typeof AuthenticatedFarmersNewRoute
  '/farms/$farmId': typeof AuthenticatedFarmsFarmIdRoute
  '/farms/new': typeof AuthenticatedFarmsNewRoute
  '/loans/$loanId': typeof AuthenticatedLoansLoanIdRoute
  '/loans/new': typeof AuthenticatedLoansNewRoute
  '/risk-assessments/$assessmentId': typeof AuthenticatedRiskAssessmentsAssessmentIdRoute
  '/saccos/$saccoId': typeof AuthenticatedSaccosSaccoIdRoute
  '/saccos/new': typeof AuthenticatedSaccosNewRoute
  '/seasons/$seasonId': typeof AuthenticatedSeasonsSeasonIdRoute
  '/seasons/new': typeof AuthenticatedSeasonsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/farmers': typeof AuthenticatedFarmersRouteWithChildren
  '/_authenticated/loans': typeof AuthenticatedLoansRouteWithChildren
  '/_authenticated/risk-assessments': typeof AuthenticatedRiskAssessmentsRouteWithChildren
  '/_authenticated/saccos': typeof AuthenticatedSaccosRouteWithChildren
  '/_authenticated/seasons': typeof AuthenticatedSeasonsRouteWithChildren
  '/_authenticated/farmers/$farmerId': typeof AuthenticatedFarmersFarmerIdRoute
  '/_authenticated/farmers/new': typeof AuthenticatedFarmersNewRoute
  '/_authenticated/farms/$farmId': typeof AuthenticatedFarmsFarmIdRoute
  '/_authenticated/farms/new': typeof AuthenticatedFarmsNewRoute
  '/_authenticated/loans/$loanId': typeof AuthenticatedLoansLoanIdRoute
  '/_authenticated/loans/new': typeof AuthenticatedLoansNewRoute
  '/_authenticated/risk-assessments/$assessmentId': typeof AuthenticatedRiskAssessmentsAssessmentIdRoute
  '/_authenticated/saccos/$saccoId': typeof AuthenticatedSaccosSaccoIdRoute
  '/_authenticated/saccos/new': typeof AuthenticatedSaccosNewRoute
  '/_authenticated/seasons/$seasonId': typeof AuthenticatedSeasonsSeasonIdRoute
  '/_authenticated/seasons/new': typeof AuthenticatedSeasonsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/farmers'
    | '/loans'
    | '/risk-assessments'
    | '/saccos'
    | '/seasons'
    | '/farmers/$farmerId'
    | '/farmers/new'
    | '/farms/$farmId'
    | '/farms/new'
    | '/loans/$loanId'
    | '/loans/new'
    | '/risk-assessments/$assessmentId'
    | '/saccos/$saccoId'
    | '/saccos/new'
    | '/seasons/$seasonId'
    | '/seasons/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/farmers'
    | '/loans'
    | '/risk-assessments'
    | '/saccos'
    | '/seasons'
    | '/farmers/$farmerId'
    | '/farmers/new'
    | '/farms/$farmId'
    | '/farms/new'
    | '/loans/$loanId'
    | '/loans/new'
    | '/risk-assessments/$assessmentId'
    | '/saccos/$saccoId'
    | '/saccos/new'
    | '/seasons/$seasonId'
    | '/seasons/new'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/dashboard'
    | '/_authenticated/farmers'
    | '/_authenticated/loans'
    | '/_authenticated/risk-assessments'
    | '/_authenticated/saccos'
    | '/_authenticated/seasons'
    | '/_authenticated/farmers/$farmerId'
    | '/_authenticated/farmers/new'
    | '/_authenticated/farms/$farmId'
    | '/_authenticated/farms/new'
    | '/_authenticated/loans/$loanId'
    | '/_authenticated/loans/new'
    | '/_authenticated/risk-assessments/$assessmentId'
    | '/_authenticated/saccos/$saccoId'
    | '/_authenticated/saccos/new'
    | '/_authenticated/seasons/$seasonId'
    | '/_authenticated/seasons/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/seasons': {
      id: '/_authenticated/seasons'
      path: '/seasons'
      fullPath: '/seasons'
      preLoaderRoute: typeof AuthenticatedSeasonsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/saccos': {
      id: '/_authenticated/saccos'
      path: '/saccos'
      fullPath: '/saccos'
      preLoaderRoute: typeof AuthenticatedSaccosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/risk-assessments': {
      id: '/_authenticated/risk-assessments'
      path: '/risk-assessments'
      fullPath: '/risk-assessments'
      preLoaderRoute: typeof AuthenticatedRiskAssessmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/loans': {
      id: '/_authenticated/loans'
      path: '/loans'
      fullPath: '/loans'
      preLoaderRoute: typeof AuthenticatedLoansRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/farmers': {
      id: '/_authenticated/farmers'
      path: '/farmers'
      fullPath: '/farmers'
      preLoaderRoute: typeof AuthenticatedFarmersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/seasons/new': {
      id: '/_authenticated/seasons/new'
      path: '/new'
      fullPath: '/seasons/new'
      preLoaderRoute: typeof AuthenticatedSeasonsNewRouteImport
      parentRoute: typeof AuthenticatedSeasonsRoute
    }
    '/_authenticated/seasons/$seasonId': {
      id: '/_authenticated/seasons/$seasonId'
      path: '/$seasonId'
      fullPath: '/seasons/$seasonId'
      preLoaderRoute: typeof AuthenticatedSeasonsSeasonIdRouteImport
      parentRoute: typeof AuthenticatedSeasonsRoute
    }
    '/_authenticated/saccos/new': {
      id: '/_authenticated/saccos/new'
      path: '/new'
      fullPath: '/saccos/new'
      preLoaderRoute: typeof AuthenticatedSaccosNewRouteImport
      parentRoute: typeof AuthenticatedSaccosRoute
    }
    '/_authenticated/saccos/$saccoId': {
      id: '/_authenticated/saccos/$saccoId'
      path: '/$saccoId'
      fullPath: '/saccos/$saccoId'
      preLoaderRoute: typeof AuthenticatedSaccosSaccoIdRouteImport
      parentRoute: typeof AuthenticatedSaccosRoute
    }
    '/_authenticated/risk-assessments/$assessmentId': {
      id: '/_authenticated/risk-assessments/$assessmentId'
      path: '/$assessmentId'
      fullPath: '/risk-assessments/$assessmentId'
      preLoaderRoute: typeof AuthenticatedRiskAssessmentsAssessmentIdRouteImport
      parentRoute: typeof AuthenticatedRiskAssessmentsRoute
    }
    '/_authenticated/loans/new': {
      id: '/_authenticated/loans/new'
      path: '/new'
      fullPath: '/loans/new'
      preLoaderRoute: typeof AuthenticatedLoansNewRouteImport
      parentRoute: typeof AuthenticatedLoansRoute
    }
    '/_authenticated/loans/$loanId': {
      id: '/_authenticated/loans/$loanId'
      path: '/$loanId'
      fullPath: '/loans/$loanId'
      preLoaderRoute: typeof AuthenticatedLoansLoanIdRouteImport
      parentRoute: typeof AuthenticatedLoansRoute
    }
    '/_authenticated/farms/new': {
      id: '/_authenticated/farms/new'
      path: '/farms/new'
      fullPath: '/farms/new'
      preLoaderRoute: typeof AuthenticatedFarmsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/farms/$farmId': {
      id: '/_authenticated/farms/$farmId'
      path: '/farms/$farmId'
      fullPath: '/farms/$farmId'
      preLoaderRoute: typeof AuthenticatedFarmsFarmIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/farmers/new': {
      id: '/_authenticated/farmers/new'
      path: '/new'
      fullPath: '/farmers/new'
      preLoaderRoute: typeof AuthenticatedFarmersNewRouteImport
      parentRoute: typeof AuthenticatedFarmersRoute
    }
    '/_authenticated/farmers/$farmerId': {
      id: '/_authenticated/farmers/$farmerId'
      path: '/$farmerId'
      fullPath: '/farmers/$farmerId'
      preLoaderRoute: typeof AuthenticatedFarmersFarmerIdRouteImport
      parentRoute: typeof AuthenticatedFarmersRoute
    }
  }
}

interface AuthenticatedFarmersRouteChildren {
  AuthenticatedFarmersFarmerIdRoute: typeof AuthenticatedFarmersFarmerIdRoute
  AuthenticatedFarmersNewRoute: typeof AuthenticatedFarmersNewRoute
}

const AuthenticatedFarmersRouteChildren: AuthenticatedFarmersRouteChildren = {
  AuthenticatedFarmersFarmerIdRoute: AuthenticatedFarmersFarmerIdRoute,
  AuthenticatedFarmersNewRoute: AuthenticatedFarmersNewRoute,
}

const AuthenticatedFarmersRouteWithChildren =
  AuthenticatedFarmersRoute._addFileChildren(AuthenticatedFarmersRouteChildren)

interface AuthenticatedLoansRouteChildren {
  AuthenticatedLoansLoanIdRoute: typeof AuthenticatedLoansLoanIdRoute
  AuthenticatedLoansNewRoute: typeof AuthenticatedLoansNewRoute
}

const AuthenticatedLoansRouteChildren: AuthenticatedLoansRouteChildren = {
  AuthenticatedLoansLoanIdRoute: AuthenticatedLoansLoanIdRoute,
  AuthenticatedLoansNewRoute: AuthenticatedLoansNewRoute,
}

const AuthenticatedLoansRouteWithChildren =
  AuthenticatedLoansRoute._addFileChildren(AuthenticatedLoansRouteChildren)

interface AuthenticatedRiskAssessmentsRouteChildren {
  AuthenticatedRiskAssessmentsAssessmentIdRoute: typeof AuthenticatedRiskAssessmentsAssessmentIdRoute
}

const AuthenticatedRiskAssessmentsRouteChildren: AuthenticatedRiskAssessmentsRouteChildren =
  {
    AuthenticatedRiskAssessmentsAssessmentIdRoute:
      AuthenticatedRiskAssessmentsAssessmentIdRoute,
  }

const AuthenticatedRiskAssessmentsRouteWithChildren =
  AuthenticatedRiskAssessmentsRoute._addFileChildren(
    AuthenticatedRiskAssessmentsRouteChildren,
  )

interface AuthenticatedSaccosRouteChildren {
  AuthenticatedSaccosSaccoIdRoute: typeof AuthenticatedSaccosSaccoIdRoute
  AuthenticatedSaccosNewRoute: typeof AuthenticatedSaccosNewRoute
}

const AuthenticatedSaccosRouteChildren: AuthenticatedSaccosRouteChildren = {
  AuthenticatedSaccosSaccoIdRoute: AuthenticatedSaccosSaccoIdRoute,
  AuthenticatedSaccosNewRoute: AuthenticatedSaccosNewRoute,
}

const AuthenticatedSaccosRouteWithChildren =
  AuthenticatedSaccosRoute._addFileChildren(AuthenticatedSaccosRouteChildren)

interface AuthenticatedSeasonsRouteChildren {
  AuthenticatedSeasonsSeasonIdRoute: typeof AuthenticatedSeasonsSeasonIdRoute
  AuthenticatedSeasonsNewRoute: typeof AuthenticatedSeasonsNewRoute
}

const AuthenticatedSeasonsRouteChildren: AuthenticatedSeasonsRouteChildren = {
  AuthenticatedSeasonsSeasonIdRoute: AuthenticatedSeasonsSeasonIdRoute,
  AuthenticatedSeasonsNewRoute: AuthenticatedSeasonsNewRoute,
}

const AuthenticatedSeasonsRouteWithChildren =
  AuthenticatedSeasonsRoute._addFileChildren(AuthenticatedSeasonsRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFarmersRoute: typeof AuthenticatedFarmersRouteWithChildren
  AuthenticatedLoansRoute: typeof AuthenticatedLoansRouteWithChildren
  AuthenticatedRiskAssessmentsRoute: typeof AuthenticatedRiskAssessmentsRouteWithChildren
  AuthenticatedSaccosRoute: typeof AuthenticatedSaccosRouteWithChildren
  AuthenticatedSeasonsRoute: typeof AuthenticatedSeasonsRouteWithChildren
  AuthenticatedFarmsFarmIdRoute: typeof AuthenticatedFarmsFarmIdRoute
  AuthenticatedFarmsNewRoute: typeof AuthenticatedFarmsNewRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFarmersRoute: AuthenticatedFarmersRouteWithChildren,
  AuthenticatedLoansRoute: AuthenticatedLoansRouteWithChildren,
  AuthenticatedRiskAssessmentsRoute:
    AuthenticatedRiskAssessmentsRouteWithChildren,
  AuthenticatedSaccosRoute: AuthenticatedSaccosRouteWithChildren,
  AuthenticatedSeasonsRoute: AuthenticatedSeasonsRouteWithChildren,
  AuthenticatedFarmsFarmIdRoute: AuthenticatedFarmsFarmIdRoute,
  AuthenticatedFarmsNewRoute: AuthenticatedFarmsNewRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
