"""
schemas/risk_assessment.py

Input and output schemas for risk assessments.

Risk assessments are generated by the system.
Users do not manually create them.
"""

from __future__ import annotations

import uuid
from datetime import datetime

from pydantic import BaseModel


class RiskAssessmentRead(BaseModel):

    id: uuid.UUID

    loan_id: uuid.UUID

    score: int

    risk_level: str

    weather_risk: int

    season_risk: int

    harvest_risk: int

    financial_risk: int

    farmer_risk: int

    action: str

    created_at: datetime

    model_config = {
        "from_attributes": True
    }


class RiskAssessmentResponse(BaseModel):

    assessment_id: uuid.UUID

    loan_id: uuid.UUID

    score: int

    risk_level: str

    action: str

    weather_risk: int

    season_risk: int

    harvest_risk: int

    financial_risk: int

    farmer_risk: int

    needs_intervention: bool